vim.g.mapleader = " "
local map = vim.api.nvim_set_keymap
map('n', '<C-h>', '<C-w>h', { noremap = true, silent = false })
map('n', '<C-j>', '<C-w>j', { noremap = true, silent = false })
map('n', '<C-k>', '<C-w>k', { noremap = true, silent = false })
map('n', '<C-l>', '<C-w>l', { noremap = true, silent = false })
map('i', 'jk', '<ESC>', { noremap = true, silent = false })
map('i', 'kj', '<ESC>', { noremap = true, silent = false })
map('v', '\\', '<gv', { noremap = true, silent = false })
map('n', '<ESC>', ':noh<cr>', { noremap = true, silent = true })
map('n', 'zx', ':HopAnywhere<cr>', { noremap = true, silent = false })
map('n', 'xc', ':HopWord<cr>', { noremap = true, silent = false })
map('n', 'cv', ':HopPattern<cr>', { noremap = true, silent = false })
map('n', 'zc', ':HopLineStart<cr>', { noremap = true, silent = false })
map('n', 'zv', ':HopVertical<cr>', { noremap = true, silent = false })
map('n', 'ss', ':split<cr>', { noremap = true, silent = false })
